package com.mspace1.model2;
// Generated Feb 9, 2017 3:09:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Tclient generated by hbm2java
 */
@Entity
@Table(name="tClient"
    ,catalog="dbTASK"
)
public class Tclient  implements java.io.Serializable {


     private Integer id;
     private String clientName;
     private String email;
     private String picPath;

    public Tclient() {
    }

    public Tclient(String clientName, String email, String picPath) {
       this.clientName = clientName;
       this.email = email;
       this.picPath = picPath;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="clientName", length=45)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="picPath", length=200)
    public String getPicPath() {
        return this.picPath;
    }
    
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }




}


