package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TallowedAlphanumerics generated by hbm2java
 */
@Entity
@Table(name="tAllowedAlphanumerics"
    ,catalog="dbSMS"
)
public class TallowedAlphanumerics  implements java.io.Serializable {


     private Long id;
     private String alphanumeric;
     private String username;

    public TallowedAlphanumerics() {
    }

    public TallowedAlphanumerics(String alphanumeric, String username) {
       this.alphanumeric = alphanumeric;
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="alphanumeric")
    public String getAlphanumeric() {
        return this.alphanumeric;
    }
    
    public void setAlphanumeric(String alphanumeric) {
        this.alphanumeric = alphanumeric;
    }

    
    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


