package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TclientAccess generated by hbm2java
 */
@Entity
@Table(name="tClientAccess"
    ,catalog="dbSMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="mobile") 
)
public class TclientAccess  implements java.io.Serializable {


     private Long id;
     private String mobile;
     private Date regDate;
     private String sms;
     private String shortCode;
     private Boolean status;
     private Byte accessTo;

    public TclientAccess() {
    }

	
    public TclientAccess(String mobile) {
        this.mobile = mobile;
    }
    public TclientAccess(String mobile, Date regDate, String sms, String shortCode, Boolean status, Byte accessTo) {
       this.mobile = mobile;
       this.regDate = regDate;
       this.sms = sms;
       this.shortCode = shortCode;
       this.status = status;
       this.accessTo = accessTo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="mobile", unique=true, nullable=false, length=14)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="regDate", length=19)
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    
    @Column(name="sms", length=65535)
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }

    
    @Column(name="short_code", length=14)
    public String getShortCode() {
        return this.shortCode;
    }
    
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="accessTo")
    public Byte getAccessTo() {
        return this.accessTo;
    }
    
    public void setAccessTo(Byte accessTo) {
        this.accessTo = accessTo;
    }




}


