package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TclientAccessTypes generated by hbm2java
 */
@Entity
@Table(name="tClientAccessTypes"
    ,catalog="dbSMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="accessTo") 
)
public class TclientAccessTypes  implements java.io.Serializable {


     private Integer id;
     private String accessTo;

    public TclientAccessTypes() {
    }

    public TclientAccessTypes(String accessTo) {
       this.accessTo = accessTo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="accessTo", unique=true, length=250)
    public String getAccessTo() {
        return this.accessTo;
    }
    
    public void setAccessTo(String accessTo) {
        this.accessTo = accessTo;
    }




}


