package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tdailyfreesms generated by hbm2java
 */
@Entity
@Table(name="tDAILYFREESMS"
    ,catalog="dbSMS"
)
public class Tdailyfreesms  implements java.io.Serializable {


     private Integer id;
     private int maxDaily;
     private Date dateSet;
     private String setBy;
     private int allowedMsgLen;
     private String trailerMsg;
     private boolean active;

    public Tdailyfreesms() {
    }

    public Tdailyfreesms(int maxDaily, Date dateSet, String setBy, int allowedMsgLen, String trailerMsg, boolean active) {
       this.maxDaily = maxDaily;
       this.dateSet = dateSet;
       this.setBy = setBy;
       this.allowedMsgLen = allowedMsgLen;
       this.trailerMsg = trailerMsg;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="max_daily", nullable=false)
    public int getMaxDaily() {
        return this.maxDaily;
    }
    
    public void setMaxDaily(int maxDaily) {
        this.maxDaily = maxDaily;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateSet", nullable=false, length=19)
    public Date getDateSet() {
        return this.dateSet;
    }
    
    public void setDateSet(Date dateSet) {
        this.dateSet = dateSet;
    }

    
    @Column(name="setBy", nullable=false, length=100)
    public String getSetBy() {
        return this.setBy;
    }
    
    public void setSetBy(String setBy) {
        this.setBy = setBy;
    }

    
    @Column(name="allowedMsgLen", nullable=false)
    public int getAllowedMsgLen() {
        return this.allowedMsgLen;
    }
    
    public void setAllowedMsgLen(int allowedMsgLen) {
        this.allowedMsgLen = allowedMsgLen;
    }

    
    @Column(name="trailerMsg", nullable=false, length=100)
    public String getTrailerMsg() {
        return this.trailerMsg;
    }
    
    public void setTrailerMsg(String trailerMsg) {
        this.trailerMsg = trailerMsg;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


