package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TdbType generated by hbm2java
 */
@Entity
@Table(name="tDbType"
    ,catalog="dbSMS"
)
public class TdbType  implements java.io.Serializable {


     private Integer id;
     private String dbtype;

    public TdbType() {
    }

    public TdbType(String dbtype) {
       this.dbtype = dbtype;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="dbtype", nullable=false, length=50)
    public String getDbtype() {
        return this.dbtype;
    }
    
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype;
    }




}


