package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tdist generated by hbm2java
 */
@Entity
@Table(name="tDIST"
    ,catalog="dbSMS"
)
public class Tdist  implements java.io.Serializable {


     private String sentby;
     private String sourceAddr;
     private String bindDesc;
       private String owner;
     private String destAddr;

    public Tdist() {
    }

    public Tdist( String sentby, String sourceAddr, String bindDesc, String owner, String destAddr) {
        
        this.sentby = sentby;
        this.sourceAddr = sourceAddr;
        this.bindDesc = bindDesc;
        this.owner = owner;
        this.destAddr = destAddr;
    }
     @Id 
    @Column(name="dest_addr", unique=true,nullable=false, length=100)
    public String getDestAddr() {
        return destAddr;
    }

    public void setDestAddr(String destAddr) {
        this.destAddr = destAddr;
    }
    
   @Column(name="owner", nullable=false, length=30)
    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }
 
 
    @Column(name="sentby", nullable=false, length=100)
    public String getSentby() {
        return this.sentby;
    }
    
    public void setSentby(String sentby) {
        this.sentby = sentby;
    }

    
    @Column(name="source_addr", nullable=false, length=100)
    public String getSourceAddr() {
        return this.sourceAddr;
    }
    
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr;
    }

    
    @Column(name="bind_desc", length=50)
    public String getBindDesc() {
        return this.bindDesc;
    }
    
    public void setBindDesc(String bindDesc) {
        this.bindDesc = bindDesc;
    }




}


