package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Temailtx generated by hbm2java
 */
@Entity
@Table(name="tEMAILTX"
    ,catalog="dbSMS"
)
public class Temailtx  implements java.io.Serializable {


     private Long id;
     private String emailFrom;
     private String emailTo;
     private String emailReplyTo;
     private String emailBody;
     private String emailcc;
     private long originalSentEmailId;
     private String subject;
     private Date timeReceived;
     private String reply;
     private boolean status;
     private Date processTime;
     private Date replyTime;
     private String attachments;
     private byte contentType;
     private String messageId;
     private String inReplyTo;
     private String reference;
     private long emailOutId;

    public Temailtx() {
    }

	
    public Temailtx(long originalSentEmailId, boolean status, byte contentType, long emailOutId) {
        this.originalSentEmailId = originalSentEmailId;
        this.status = status;
        this.contentType = contentType;
        this.emailOutId = emailOutId;
    }
    public Temailtx(String emailFrom, String emailTo, String emailReplyTo, String emailBody, String emailcc, long originalSentEmailId, String subject, Date timeReceived, String reply, boolean status, Date processTime, Date replyTime, String attachments, byte contentType, String messageId, String inReplyTo, String reference, long emailOutId) {
       this.emailFrom = emailFrom;
       this.emailTo = emailTo;
       this.emailReplyTo = emailReplyTo;
       this.emailBody = emailBody;
       this.emailcc = emailcc;
       this.originalSentEmailId = originalSentEmailId;
       this.subject = subject;
       this.timeReceived = timeReceived;
       this.reply = reply;
       this.status = status;
       this.processTime = processTime;
       this.replyTime = replyTime;
       this.attachments = attachments;
       this.contentType = contentType;
       this.messageId = messageId;
       this.inReplyTo = inReplyTo;
       this.reference = reference;
       this.emailOutId = emailOutId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="emailFrom", length=200)
    public String getEmailFrom() {
        return this.emailFrom;
    }
    
    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom;
    }

    
    @Column(name="emailTo", length=200)
    public String getEmailTo() {
        return this.emailTo;
    }
    
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }

    
    @Column(name="emailReplyTo", length=200)
    public String getEmailReplyTo() {
        return this.emailReplyTo;
    }
    
    public void setEmailReplyTo(String emailReplyTo) {
        this.emailReplyTo = emailReplyTo;
    }

    
    @Column(name="emailBody", length=65535)
    public String getEmailBody() {
        return this.emailBody;
    }
    
    public void setEmailBody(String emailBody) {
        this.emailBody = emailBody;
    }

    
    @Column(name="emailcc", length=100)
    public String getEmailcc() {
        return this.emailcc;
    }
    
    public void setEmailcc(String emailcc) {
        this.emailcc = emailcc;
    }

    
    @Column(name="originalSentEmailId", nullable=false)
    public long getOriginalSentEmailId() {
        return this.originalSentEmailId;
    }
    
    public void setOriginalSentEmailId(long originalSentEmailId) {
        this.originalSentEmailId = originalSentEmailId;
    }

    
    @Column(name="subject", length=250)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeReceived", length=19)
    public Date getTimeReceived() {
        return this.timeReceived;
    }
    
    public void setTimeReceived(Date timeReceived) {
        this.timeReceived = timeReceived;
    }

    
    @Column(name="reply", length=65535)
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="processTime", length=19)
    public Date getProcessTime() {
        return this.processTime;
    }
    
    public void setProcessTime(Date processTime) {
        this.processTime = processTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="replyTime", length=19)
    public Date getReplyTime() {
        return this.replyTime;
    }
    
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    
    @Column(name="attachments", length=250)
    public String getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(String attachments) {
        this.attachments = attachments;
    }

    
    @Column(name="contentType", nullable=false)
    public byte getContentType() {
        return this.contentType;
    }
    
    public void setContentType(byte contentType) {
        this.contentType = contentType;
    }

    
    @Column(name="message_id", length=250)
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="inReplyTo", length=250)
    public String getInReplyTo() {
        return this.inReplyTo;
    }
    
    public void setInReplyTo(String inReplyTo) {
        this.inReplyTo = inReplyTo;
    }

    
    @Column(name="reference", length=250)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="emailOutId", nullable=false)
    public long getEmailOutId() {
        return this.emailOutId;
    }
    
    public void setEmailOutId(long emailOutId) {
        this.emailOutId = emailOutId;
    }




}


