package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Temailin generated by hbm2java
 */
@Entity
@Table(name="tEMAILIN"
    ,catalog="dbSMS"
)
public class Temailin  implements java.io.Serializable {


     private Long id;
     private String emailFrom;
     private String emailTo;
     private String emailReplyTo;
     private String subject;
     private String body;
     private String attachments;
     private Boolean status;
     private Date timeReceived;
     private byte contentType;
     private String messageId;
     private String inReplyTo;
     private String reference;

    public Temailin() {
    }

	
    public Temailin(byte contentType, String messageId, String inReplyTo, String reference) {
        this.contentType = contentType;
        this.messageId = messageId;
        this.inReplyTo = inReplyTo;
        this.reference = reference;
    }
    public Temailin(String emailFrom, String emailTo, String emailReplyTo, String subject, String body, String attachments, Boolean status, Date timeReceived, byte contentType, String messageId, String inReplyTo, String reference) {
       this.emailFrom = emailFrom;
       this.emailTo = emailTo;
       this.emailReplyTo = emailReplyTo;
       this.subject = subject;
       this.body = body;
       this.attachments = attachments;
       this.status = status;
       this.timeReceived = timeReceived;
       this.contentType = contentType;
       this.messageId = messageId;
       this.inReplyTo = inReplyTo;
       this.reference = reference;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="emailFrom", length=200)
    public String getEmailFrom() {
        return this.emailFrom;
    }
    
    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom;
    }

    
    @Column(name="emailTo", length=200)
    public String getEmailTo() {
        return this.emailTo;
    }
    
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }

    
    @Column(name="emailReplyTo", length=200)
    public String getEmailReplyTo() {
        return this.emailReplyTo;
    }
    
    public void setEmailReplyTo(String emailReplyTo) {
        this.emailReplyTo = emailReplyTo;
    }

    
    @Column(name="subject", length=250)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="body", length=65535)
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="attachments", length=65535)
    public String getAttachments() {
        return this.attachments;
    }
    
    public void setAttachments(String attachments) {
        this.attachments = attachments;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeReceived", length=19)
    public Date getTimeReceived() {
        return this.timeReceived;
    }
    
    public void setTimeReceived(Date timeReceived) {
        this.timeReceived = timeReceived;
    }

    
    @Column(name="contentType", nullable=false)
    public byte getContentType() {
        return this.contentType;
    }
    
    public void setContentType(byte contentType) {
        this.contentType = contentType;
    }

    
    @Column(name="message_id", nullable=false, length=250)
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="inReplyTo", nullable=false, length=250)
    public String getInReplyTo() {
        return this.inReplyTo;
    }
    
    public void setInReplyTo(String inReplyTo) {
        this.inReplyTo = inReplyTo;
    }

    
    @Column(name="reference", nullable=false)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }




}


