package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Temailout generated by hbm2java
 */
@Entity
@Table(name="tEMAILOUT"
    ,catalog="dbSMS"
)
public class Temailout  implements java.io.Serializable {


     private Long id;
     private String policyNo;
     private String mobile;
     private String name;
     private String emailSrc;
     private String emailTo;
     private String emailReplyTo;
     private String emailBody;
     private String emailcc;
     private String subject;
     private String attachment;
     private String messageId;
     private String user;
     private Date timesubmitted;
     private boolean emailType;
     private Boolean status;

    public Temailout() {
    }

	
    public Temailout(boolean emailType) {
        this.emailType = emailType;
    }
    public Temailout(String policyNo, String mobile, String name, String emailSrc, String emailTo, String emailReplyTo, String emailBody, String emailcc, String subject, String attachment, String messageId, String user, Date timesubmitted, boolean emailType, Boolean status) {
       this.policyNo = policyNo;
       this.mobile = mobile;
       this.name = name;
       this.emailSrc = emailSrc;
       this.emailTo = emailTo;
       this.emailReplyTo = emailReplyTo;
       this.emailBody = emailBody;
       this.emailcc = emailcc;
       this.subject = subject;
       this.attachment = attachment;
       this.messageId = messageId;
       this.user = user;
       this.timesubmitted = timesubmitted;
       this.emailType = emailType;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="policyNo", length=100)
    public String getPolicyNo() {
        return this.policyNo;
    }
    
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    
    @Column(name="mobile", length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="emailSrc", length=200)
    public String getEmailSrc() {
        return this.emailSrc;
    }
    
    public void setEmailSrc(String emailSrc) {
        this.emailSrc = emailSrc;
    }

    
    @Column(name="emailTo", length=250)
    public String getEmailTo() {
        return this.emailTo;
    }
    
    public void setEmailTo(String emailTo) {
        this.emailTo = emailTo;
    }

    
    @Column(name="emailReplyTo", length=200)
    public String getEmailReplyTo() {
        return this.emailReplyTo;
    }
    
    public void setEmailReplyTo(String emailReplyTo) {
        this.emailReplyTo = emailReplyTo;
    }

    
    @Column(name="emailBody", length=65535)
    public String getEmailBody() {
        return this.emailBody;
    }
    
    public void setEmailBody(String emailBody) {
        this.emailBody = emailBody;
    }

    
    @Column(name="emailcc", length=100)
    public String getEmailcc() {
        return this.emailcc;
    }
    
    public void setEmailcc(String emailcc) {
        this.emailcc = emailcc;
    }

    
    @Column(name="subject", length=100)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="attachment", length=250)
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    
    @Column(name="message_id", length=250)
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="user", length=100)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timesubmitted", length=19)
    public Date getTimesubmitted() {
        return this.timesubmitted;
    }
    
    public void setTimesubmitted(Date timesubmitted) {
        this.timesubmitted = timesubmitted;
    }

    
    @Column(name="emailType", nullable=false)
    public boolean isEmailType() {
        return this.emailType;
    }
    
    public void setEmailType(boolean emailType) {
        this.emailType = emailType;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


