package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TemailToSms generated by hbm2java
 */
@Entity
@Table(name="tEmailToSMS"
    ,catalog="dbSMS"
)
public class TemailToSms  implements java.io.Serializable {


     private Integer id;
     private String receiver;
     private String incomingMail;
     private Integer status;

    public TemailToSms() {
    }

    public TemailToSms(String receiver, String incomingMail, Integer status) {
       this.receiver = receiver;
       this.incomingMail = incomingMail;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="receiver", length=65535)
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    
    @Column(name="incomingMail", length=45)
    public String getIncomingMail() {
        return this.incomingMail;
    }
    
    public void setIncomingMail(String incomingMail) {
        this.incomingMail = incomingMail;
    }

    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


