package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Texcelsmstosend generated by hbm2java
 */
@Entity
@Table(name="tEXCELSMSTOSEND"
    ,catalog="dbSMS"
)
public class Texcelsmstosend  implements java.io.Serializable {


     private Integer id;
     private String file;
     private String sheet;
     private String mobileColumn;
     private String messagetemplate;
     private Date timeTosend;
     private String user;
     private String source;
     private int deliverFrequency;
     private Date timeSubmitted;
     private byte processed;

    public Texcelsmstosend() {
    }

	
    public Texcelsmstosend(String file, String sheet, String mobileColumn, String messagetemplate, Date timeTosend, String user, String source, int deliverFrequency, byte processed) {
        this.file = file;
        this.sheet = sheet;
        this.mobileColumn = mobileColumn;
        this.messagetemplate = messagetemplate;
        this.timeTosend = timeTosend;
        this.user = user;
        this.source = source;
        this.deliverFrequency = deliverFrequency;
        this.processed = processed;
    }
    public Texcelsmstosend(String file, String sheet, String mobileColumn, String messagetemplate, Date timeTosend, String user, String source, int deliverFrequency, Date timeSubmitted, byte processed) {
       this.file = file;
       this.sheet = sheet;
       this.mobileColumn = mobileColumn;
       this.messagetemplate = messagetemplate;
       this.timeTosend = timeTosend;
       this.user = user;
       this.source = source;
       this.deliverFrequency = deliverFrequency;
       this.timeSubmitted = timeSubmitted;
       this.processed = processed;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="file", nullable=false, length=65535)
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }

    
    @Column(name="sheet", nullable=false, length=50)
    public String getSheet() {
        return this.sheet;
    }
    
    public void setSheet(String sheet) {
        this.sheet = sheet;
    }

    
    @Column(name="mobileColumn", nullable=false, length=20)
    public String getMobileColumn() {
        return this.mobileColumn;
    }
    
    public void setMobileColumn(String mobileColumn) {
        this.mobileColumn = mobileColumn;
    }

    
    @Column(name="messagetemplate", nullable=false, length=65535)
    public String getMessagetemplate() {
        return this.messagetemplate;
    }
    
    public void setMessagetemplate(String messagetemplate) {
        this.messagetemplate = messagetemplate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeTosend", nullable=false, length=19)
    public Date getTimeTosend() {
        return this.timeTosend;
    }
    
    public void setTimeTosend(Date timeTosend) {
        this.timeTosend = timeTosend;
    }

    
    @Column(name="user", nullable=false, length=20)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="source", nullable=false, length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="deliverFrequency", nullable=false)
    public int getDeliverFrequency() {
        return this.deliverFrequency;
    }
    
    public void setDeliverFrequency(int deliverFrequency) {
        this.deliverFrequency = deliverFrequency;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_submitted", length=19)
    public Date getTimeSubmitted() {
        return this.timeSubmitted;
    }
    
    public void setTimeSubmitted(Date timeSubmitted) {
        this.timeSubmitted = timeSubmitted;
    }

    
    @Column(name="processed", nullable=false)
    public byte getProcessed() {
        return this.processed;
    }
    
    public void setProcessed(byte processed) {
        this.processed = processed;
    }




}


