package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TexcelIntegration generated by hbm2java
 */
@Entity
@Table(name="tExcelIntegration"
    ,catalog="dbSMS"
)
public class TexcelIntegration  implements java.io.Serializable {


     private String user;
     private String msg;
     private String fromPart;

    public TexcelIntegration() {
    }

    public TexcelIntegration(String user, String msg, String fromPart) {
       this.user = user;
       this.msg = msg;
       this.fromPart = fromPart;
    }
   
     @Id 

    
    @Column(name="user", unique=true, nullable=false, length=100)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="msg", nullable=false, length=65535)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }

    
    @Column(name="fromPart", nullable=false, length=13)
    public String getFromPart() {
        return this.fromPart;
    }
    
    public void setFromPart(String fromPart) {
        this.fromPart = fromPart;
    }




}


