package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmanageCredits generated by hbm2java
 */
@Entity
@Table(name="tManageCredits"
    ,catalog="dbSMS"
)
public class TmanageCredits  implements java.io.Serializable {


     private Long id;
     private String username;
     private Character actionType;
     private Date actionTime;
     private Integer numCredits;
     private Integer previousBalance;
     private Integer newBalance;

    public TmanageCredits() {
    }

    public TmanageCredits(String username, Character actionType, Date actionTime, Integer numCredits, Integer previousBalance, Integer newBalance) {
       this.username = username;
       this.actionType = actionType;
       this.actionTime = actionTime;
       this.numCredits = numCredits;
       this.previousBalance = previousBalance;
       this.newBalance = newBalance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="username")
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="actionType", length=1)
    public Character getActionType() {
        return this.actionType;
    }
    
    public void setActionType(Character actionType) {
        this.actionType = actionType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="actionTime", length=19)
    public Date getActionTime() {
        return this.actionTime;
    }
    
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }

    
    @Column(name="numCredits")
    public Integer getNumCredits() {
        return this.numCredits;
    }
    
    public void setNumCredits(Integer numCredits) {
        this.numCredits = numCredits;
    }

    
    @Column(name="previous_balance")
    public Integer getPreviousBalance() {
        return this.previousBalance;
    }
    
    public void setPreviousBalance(Integer previousBalance) {
        this.previousBalance = previousBalance;
    }

    
    @Column(name="new_balance")
    public Integer getNewBalance() {
        return this.newBalance;
    }
    
    public void setNewBalance(Integer newBalance) {
        this.newBalance = newBalance;
    }




}


