package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmspaceShortCodesIn generated by hbm2java
 */
@Entity
@Table(name="tMspaceShortCodesIn"
    ,catalog="dbSMS"
)
public class TmspaceShortCodesIn  implements java.io.Serializable {


     private Long id;
     private String seqNo;
     private String shortMessage;
     private String sourceAddr;
     private String destinationAddr;
     private String esmClass;
     private Date timereceived;
     private Date timeSubmitted;
     private String errorinfo;
     private Boolean status;

    public TmspaceShortCodesIn() {
    }

    public TmspaceShortCodesIn(String seqNo, String shortMessage, String sourceAddr, String destinationAddr, String esmClass, Date timereceived, Date timeSubmitted, String errorinfo, Boolean status) {
       this.seqNo = seqNo;
       this.shortMessage = shortMessage;
       this.sourceAddr = sourceAddr;
       this.destinationAddr = destinationAddr;
       this.esmClass = esmClass;
       this.timereceived = timereceived;
       this.timeSubmitted = timeSubmitted;
       this.errorinfo = errorinfo;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="seqNo", length=100)
    public String getSeqNo() {
        return this.seqNo;
    }
    
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo;
    }

    
    @Column(name="short_message", length=65535)
    public String getShortMessage() {
        return this.shortMessage;
    }
    
    public void setShortMessage(String shortMessage) {
        this.shortMessage = shortMessage;
    }

    
    @Column(name="source_addr", length=20)
    public String getSourceAddr() {
        return this.sourceAddr;
    }
    
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr;
    }

    
    @Column(name="destination_addr", length=100)
    public String getDestinationAddr() {
        return this.destinationAddr;
    }
    
    public void setDestinationAddr(String destinationAddr) {
        this.destinationAddr = destinationAddr;
    }

    
    @Column(name="esm_class", length=2)
    public String getEsmClass() {
        return this.esmClass;
    }
    
    public void setEsmClass(String esmClass) {
        this.esmClass = esmClass;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timereceived", length=19)
    public Date getTimereceived() {
        return this.timereceived;
    }
    
    public void setTimereceived(Date timereceived) {
        this.timereceived = timereceived;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_submitted", length=19)
    public Date getTimeSubmitted() {
        return this.timeSubmitted;
    }
    
    public void setTimeSubmitted(Date timeSubmitted) {
        this.timeSubmitted = timeSubmitted;
    }

    
    @Column(name="errorinfo", length=100)
    public String getErrorinfo() {
        return this.errorinfo;
    }
    
    public void setErrorinfo(String errorinfo) {
        this.errorinfo = errorinfo;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


