package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TremoteConnections generated by hbm2java
 */
@Entity
@Table(name="tRemoteConnections"
    ,catalog="dbSMS"
)
public class TremoteConnections  implements java.io.Serializable {


     private Long id;
     private String ip;
     private String dbname;
     private String username;
     private String password;
     private String dbtype;

    public TremoteConnections() {
    }

	
    public TremoteConnections(String ip, String dbname, String username, String password) {
        this.ip = ip;
        this.dbname = dbname;
        this.username = username;
        this.password = password;
    }
    public TremoteConnections(String ip, String dbname, String username, String password, String dbtype) {
       this.ip = ip;
       this.dbname = dbname;
       this.username = username;
       this.password = password;
       this.dbtype = dbtype;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="ip", nullable=false, length=100)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    @Column(name="dbname", nullable=false, length=100)
    public String getDbname() {
        return this.dbname;
    }
    
    public void setDbname(String dbname) {
        this.dbname = dbname;
    }

    
    @Column(name="username", nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="dbtype", length=100)
    public String getDbtype() {
        return this.dbtype;
    }
    
    public void setDbtype(String dbtype) {
        this.dbtype = dbtype;
    }




}


