package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Trules generated by hbm2java
 */
@Entity
@Table(name="tRULES"
    ,catalog="dbSMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="RuleName") 
)
public class Trules  implements java.io.Serializable {


     private Long id;
     private String ruleName;
     private long ruleType;
     private String filename;
     private String dbName;
     private String tableName;
     private String statement;
     private String message;
     private String telno;
     private String dest;
     private String ipaddr;
     private Byte exOrder;
     private String reply;

    public Trules() {
    }

	
    public Trules(String ruleName, long ruleType, String filename, String dbName, String tableName, String statement) {
        this.ruleName = ruleName;
        this.ruleType = ruleType;
        this.filename = filename;
        this.dbName = dbName;
        this.tableName = tableName;
        this.statement = statement;
    }
    public Trules(String ruleName, long ruleType, String filename, String dbName, String tableName, String statement, String message, String telno, String dest, String ipaddr, Byte exOrder, String reply) {
       this.ruleName = ruleName;
       this.ruleType = ruleType;
       this.filename = filename;
       this.dbName = dbName;
       this.tableName = tableName;
       this.statement = statement;
       this.message = message;
       this.telno = telno;
       this.dest = dest;
       this.ipaddr = ipaddr;
       this.exOrder = exOrder;
       this.reply = reply;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="RuleName", unique=true, nullable=false, length=100)
    public String getRuleName() {
        return this.ruleName;
    }
    
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    
    @Column(name="RuleType", nullable=false)
    public long getRuleType() {
        return this.ruleType;
    }
    
    public void setRuleType(long ruleType) {
        this.ruleType = ruleType;
    }

    
    @Column(name="Filename", nullable=false, length=250)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="db_name", nullable=false, length=100)
    public String getDbName() {
        return this.dbName;
    }
    
    public void setDbName(String dbName) {
        this.dbName = dbName;
    }

    
    @Column(name="table_name", nullable=false, length=100)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    
    @Column(name="statement", nullable=false)
    public String getStatement() {
        return this.statement;
    }
    
    public void setStatement(String statement) {
        this.statement = statement;
    }

    
    @Column(name="message", length=20)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="telno", length=20)
    public String getTelno() {
        return this.telno;
    }
    
    public void setTelno(String telno) {
        this.telno = telno;
    }

    
    @Column(name="dest")
    public String getDest() {
        return this.dest;
    }
    
    public void setDest(String dest) {
        this.dest = dest;
    }

    
    @Column(name="ipaddr", length=20)
    public String getIpaddr() {
        return this.ipaddr;
    }
    
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    
    @Column(name="ex_order")
    public Byte getExOrder() {
        return this.exOrder;
    }
    
    public void setExOrder(Byte exOrder) {
        this.exOrder = exOrder;
    }

    
    @Column(name="reply", length=160)
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }




}


