package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsavedMessages generated by hbm2java
 */
@Entity
@Table(name="tSAVED_MESSAGES"
    ,catalog="dbSMS"
)
public class TsavedMessages  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int userId;
     private byte type;
     private String message;

    public TsavedMessages() {
    }

    public TsavedMessages(String name, int userId, byte type, String message) {
       this.name = name;
       this.userId = userId;
       this.type = type;
       this.message = message;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="User_id", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="type", nullable=false)
    public byte getType() {
        return this.type;
    }
    
    public void setType(byte type) {
        this.type = type;
    }

    
    @Column(name="message", nullable=false, length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


