package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tschedule generated by hbm2java
 */
@Entity
@Table(name="tSCHEDULE"
    ,catalog="dbSMS"
)
public class Tschedule  implements java.io.Serializable {


     private Long id;
     private String name;
     private Date timeToRun;
     private int minute;
     private int hour;
     private int day;
     private int week;
     private String filename;
     private boolean status;
     private String adminEmail;

    public Tschedule() {
    }

	
    public Tschedule(String name, Date timeToRun, int minute, int hour, int day, int week, String filename, boolean status) {
        this.name = name;
        this.timeToRun = timeToRun;
        this.minute = minute;
        this.hour = hour;
        this.day = day;
        this.week = week;
        this.filename = filename;
        this.status = status;
    }
    public Tschedule(String name, Date timeToRun, int minute, int hour, int day, int week, String filename, boolean status, String adminEmail) {
       this.name = name;
       this.timeToRun = timeToRun;
       this.minute = minute;
       this.hour = hour;
       this.day = day;
       this.week = week;
       this.filename = filename;
       this.status = status;
       this.adminEmail = adminEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="time_to_run", nullable=false, length=19)
    public Date getTimeToRun() {
        return this.timeToRun;
    }
    
    public void setTimeToRun(Date timeToRun) {
        this.timeToRun = timeToRun;
    }

    
    @Column(name="minute", nullable=false)
    public int getMinute() {
        return this.minute;
    }
    
    public void setMinute(int minute) {
        this.minute = minute;
    }

    
    @Column(name="hour", nullable=false)
    public int getHour() {
        return this.hour;
    }
    
    public void setHour(int hour) {
        this.hour = hour;
    }

    
    @Column(name="day", nullable=false)
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }

    
    @Column(name="week", nullable=false)
    public int getWeek() {
        return this.week;
    }
    
    public void setWeek(int week) {
        this.week = week;
    }

    
    @Column(name="filename", nullable=false, length=250)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="adminEmail", length=100)
    public String getAdminEmail() {
        return this.adminEmail;
    }
    
    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }




}


