package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsdp generated by hbm2java
 */
@Entity
@Table(name="tSDP"
    ,catalog="dbSMS"
)
public class Tsdp  implements java.io.Serializable {


     private Integer id;
     private int spId;
     private String serviceId;
     private String spPasswordMd5;
     private String spPasswordTime;
     private String shortCode;
     private Boolean shortCodeType;
     private int bulkAccessCode;
     private Boolean active;

    public Tsdp() {
    }

	
    public Tsdp(int spId, String serviceId, String spPasswordMd5, String spPasswordTime, String shortCode, int bulkAccessCode) {
        this.spId = spId;
        this.serviceId = serviceId;
        this.spPasswordMd5 = spPasswordMd5;
        this.spPasswordTime = spPasswordTime;
        this.shortCode = shortCode;
        this.bulkAccessCode = bulkAccessCode;
    }
    public Tsdp(int spId, String serviceId, String spPasswordMd5, String spPasswordTime, String shortCode, Boolean shortCodeType, int bulkAccessCode, Boolean active) {
       this.spId = spId;
       this.serviceId = serviceId;
       this.spPasswordMd5 = spPasswordMd5;
       this.spPasswordTime = spPasswordTime;
       this.shortCode = shortCode;
       this.shortCodeType = shortCodeType;
       this.bulkAccessCode = bulkAccessCode;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="spID", nullable=false)
    public int getSpId() {
        return this.spId;
    }
    
    public void setSpId(int spId) {
        this.spId = spId;
    }

    
    @Column(name="serviceID", nullable=false, length=45)
    public String getServiceId() {
        return this.serviceId;
    }
    
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId;
    }

    
    @Column(name="spPasswordMD5", nullable=false, length=100)
    public String getSpPasswordMd5() {
        return this.spPasswordMd5;
    }
    
    public void setSpPasswordMd5(String spPasswordMd5) {
        this.spPasswordMd5 = spPasswordMd5;
    }

    
    @Column(name="spPasswordTime", nullable=false, length=45)
    public String getSpPasswordTime() {
        return this.spPasswordTime;
    }
    
    public void setSpPasswordTime(String spPasswordTime) {
        this.spPasswordTime = spPasswordTime;
    }

    
    @Column(name="short_code", nullable=false, length=45)
    public String getShortCode() {
        return this.shortCode;
    }
    
    public void setShortCode(String shortCode) {
        this.shortCode = shortCode;
    }

    
    @Column(name="short_code_type")
    public Boolean getShortCodeType() {
        return this.shortCodeType;
    }
    
    public void setShortCodeType(Boolean shortCodeType) {
        this.shortCodeType = shortCodeType;
    }

    
    @Column(name="bulkAccessCode", nullable=false)
    public int getBulkAccessCode() {
        return this.bulkAccessCode;
    }
    
    public void setBulkAccessCode(int bulkAccessCode) {
        this.bulkAccessCode = bulkAccessCode;
    }

    
    @Column(name="active")
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


