package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TsdpPasswords generated by hbm2java
 */
@Entity
@Table(name="tSdpPasswords"
    ,catalog="dbSMS"
)
public class TsdpPasswords  implements java.io.Serializable {


     private Integer id;
     private String timestamp;
     private String spId;
     private String md5;
     private Date dateUpdated;

    public TsdpPasswords() {
    }

	
    public TsdpPasswords(String spId, String md5) {
        this.spId = spId;
        this.md5 = md5;
    }
    public TsdpPasswords(String spId, String md5, Date dateUpdated) {
       this.spId = spId;
       this.md5 = md5;
       this.dateUpdated = dateUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Version
    @Column(name="timestamp", nullable=false, length=100)
    public String getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    
    @Column(name="spID", nullable=false, length=100)
    public String getSpId() {
        return this.spId;
    }
    
    public void setSpId(String spId) {
        this.spId = spId;
    }

    
    @Column(name="md5", nullable=false, length=100)
    public String getMd5() {
        return this.md5;
    }
    
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateUpdated", length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }




}


