package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TshortCodes generated by hbm2java
 */
@Entity
@Table(name="tShortCodes"
    ,catalog="dbSMS"
)
public class TshortCodes  implements java.io.Serializable {


     private Integer id;
     private String shortcode;

    public TshortCodes() {
    }

    public TshortCodes(String shortcode) {
       this.shortcode = shortcode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="shortcode", length=45)
    public String getShortcode() {
        return this.shortcode;
    }
    
    public void setShortcode(String shortcode) {
        this.shortcode = shortcode;
    }




}


