package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tsignupuser generated by hbm2java
 */
@Entity
@Table(name="tSIGNUPUSER"
    ,catalog="dbSMS"
    , uniqueConstraints = {@UniqueConstraint(columnNames="user_id"), @UniqueConstraint(columnNames="contact_number")} 
)
public class Tsignupuser  implements java.io.Serializable {


     private Long id;
     private int userId;
     private String fname;
     private String lname;
     private String contactNumber;
     private String password;
     private String gender;
     private String email;
     private Date bday;
     private int age;
     private String mstatus;
     private String location;
     private String zip;
     private String edu;
     private String job;
     private String occupation;
     private String income;
     private String hobbies;
     private String sports;
     private String newspaper;
     private String radio;
     private String tv;
     private String magazine;
     private String findAboutUs;
     private Date dateActivated;
     private short active;

    public Tsignupuser() {
    }

    public Tsignupuser(int userId, String fname, String lname, String contactNumber, String password, String gender, String email, Date bday, int age, String mstatus, String location, String zip, String edu, String job, String occupation, String income, String hobbies, String sports, String newspaper, String radio, String tv, String magazine, String findAboutUs, Date dateActivated, short active) {
       this.userId = userId;
       this.fname = fname;
       this.lname = lname;
       this.contactNumber = contactNumber;
       this.password = password;
       this.gender = gender;
       this.email = email;
       this.bday = bday;
       this.age = age;
       this.mstatus = mstatus;
       this.location = location;
       this.zip = zip;
       this.edu = edu;
       this.job = job;
       this.occupation = occupation;
       this.income = income;
       this.hobbies = hobbies;
       this.sports = sports;
       this.newspaper = newspaper;
       this.radio = radio;
       this.tv = tv;
       this.magazine = magazine;
       this.findAboutUs = findAboutUs;
       this.dateActivated = dateActivated;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="user_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="fname", nullable=false, length=100)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="lname", nullable=false, length=100)
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }

    
    @Column(name="contact_number", unique=true, nullable=false, length=14)
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="gender", nullable=false, length=100)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="email", nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bday", nullable=false, length=10)
    public Date getBday() {
        return this.bday;
    }
    
    public void setBday(Date bday) {
        this.bday = bday;
    }

    
    @Column(name="age", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="mStatus", nullable=false, length=100)
    public String getMstatus() {
        return this.mstatus;
    }
    
    public void setMstatus(String mstatus) {
        this.mstatus = mstatus;
    }

    
    @Column(name="location", nullable=false, length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="zip", nullable=false, length=100)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="edu", nullable=false, length=100)
    public String getEdu() {
        return this.edu;
    }
    
    public void setEdu(String edu) {
        this.edu = edu;
    }

    
    @Column(name="job", nullable=false, length=100)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="occupation", nullable=false, length=100)
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="income", nullable=false, length=100)
    public String getIncome() {
        return this.income;
    }
    
    public void setIncome(String income) {
        this.income = income;
    }

    
    @Column(name="hobbies", nullable=false, length=100)
    public String getHobbies() {
        return this.hobbies;
    }
    
    public void setHobbies(String hobbies) {
        this.hobbies = hobbies;
    }

    
    @Column(name="sports", nullable=false, length=100)
    public String getSports() {
        return this.sports;
    }
    
    public void setSports(String sports) {
        this.sports = sports;
    }

    
    @Column(name="newspaper", nullable=false, length=100)
    public String getNewspaper() {
        return this.newspaper;
    }
    
    public void setNewspaper(String newspaper) {
        this.newspaper = newspaper;
    }

    
    @Column(name="radio", nullable=false, length=100)
    public String getRadio() {
        return this.radio;
    }
    
    public void setRadio(String radio) {
        this.radio = radio;
    }

    
    @Column(name="tv", nullable=false, length=100)
    public String getTv() {
        return this.tv;
    }
    
    public void setTv(String tv) {
        this.tv = tv;
    }

    
    @Column(name="magazine", nullable=false, length=100)
    public String getMagazine() {
        return this.magazine;
    }
    
    public void setMagazine(String magazine) {
        this.magazine = magazine;
    }

    
    @Column(name="findAboutUs", nullable=false, length=100)
    public String getFindAboutUs() {
        return this.findAboutUs;
    }
    
    public void setFindAboutUs(String findAboutUs) {
        this.findAboutUs = findAboutUs;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateActivated", nullable=false, length=19)
    public Date getDateActivated() {
        return this.dateActivated;
    }
    
    public void setDateActivated(Date dateActivated) {
        this.dateActivated = dateActivated;
    }

    
    @Column(name="active", nullable=false)
    public short getActive() {
        return this.active;
    }
    
    public void setActive(short active) {
        this.active = active;
    }




}


