package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tsmsstatus generated by hbm2java
 */
@Entity
@Table(name="tSMSSTATUS"
    ,catalog="dbSMS"
)
public class Tsmsstatus  implements java.io.Serializable {


     private String id;
     private String desctiption;

    public Tsmsstatus() {
    }

    public Tsmsstatus(String id, String desctiption) {
       this.id = id;
       this.desctiption = desctiption;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=100)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="desctiption", nullable=false, length=100)
    public String getDesctiption() {
        return this.desctiption;
    }
    
    public void setDesctiption(String desctiption) {
        this.desctiption = desctiption;
    }




}


