package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tstatements generated by hbm2java
 */
@Entity
@Table(name="tSTATEMENTS"
    ,catalog="dbSMS"
)
public class Tstatements  implements java.io.Serializable {


     private Long id;
     private String policyNo;
     private String mobile;
     private String name;
     private String email;
     private String filename;
     private String statement;
     private Date dateLoaded;
     private Date dateSent;
     private long emailoutId;
     private Boolean status;

    public Tstatements() {
    }

	
    public Tstatements(String statement, long emailoutId) {
        this.statement = statement;
        this.emailoutId = emailoutId;
    }
    public Tstatements(String policyNo, String mobile, String name, String email, String filename, String statement, Date dateLoaded, Date dateSent, long emailoutId, Boolean status) {
       this.policyNo = policyNo;
       this.mobile = mobile;
       this.name = name;
       this.email = email;
       this.filename = filename;
       this.statement = statement;
       this.dateLoaded = dateLoaded;
       this.dateSent = dateSent;
       this.emailoutId = emailoutId;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="policyNo", length=100)
    public String getPolicyNo() {
        return this.policyNo;
    }
    
    public void setPolicyNo(String policyNo) {
        this.policyNo = policyNo;
    }

    
    @Column(name="mobile", length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="filename", length=100)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="statement", nullable=false, length=65535)
    public String getStatement() {
        return this.statement;
    }
    
    public void setStatement(String statement) {
        this.statement = statement;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateLoaded", length=19)
    public Date getDateLoaded() {
        return this.dateLoaded;
    }
    
    public void setDateLoaded(Date dateLoaded) {
        this.dateLoaded = dateLoaded;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dateSent", length=19)
    public Date getDateSent() {
        return this.dateSent;
    }
    
    public void setDateSent(Date dateSent) {
        this.dateSent = dateSent;
    }

    
    @Column(name="emailoutId", nullable=false)
    public long getEmailoutId() {
        return this.emailoutId;
    }
    
    public void setEmailoutId(long emailoutId) {
        this.emailoutId = emailoutId;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


