package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tstatsout generated by hbm2java
 */
@Entity
@Table(name="tSTATSOUT"
    ,catalog="dbSMS"
)
public class Tstatsout  implements java.io.Serializable {


     private TstatsoutId id;
     private long total;
     private long safaricom;
     private long cellc;
     private long celltel;
     private long other;
     private Long totalFailed;
     private Long cellcFailed;
     private long celltelFailed;
     private Long safaricomFailed;
     private Long otherFailed;

    public Tstatsout() {
    }

	
    public Tstatsout(TstatsoutId id, long total, long safaricom, long cellc, long celltel, long other, long celltelFailed) {
        this.id = id;
        this.total = total;
        this.safaricom = safaricom;
        this.cellc = cellc;
        this.celltel = celltel;
        this.other = other;
        this.celltelFailed = celltelFailed;
    }
    public Tstatsout(TstatsoutId id, long total, long safaricom, long cellc, long celltel, long other, Long totalFailed, Long cellcFailed, long celltelFailed, Long safaricomFailed, Long otherFailed) {
       this.id = id;
       this.total = total;
       this.safaricom = safaricom;
       this.cellc = cellc;
       this.celltel = celltel;
       this.other = other;
       this.totalFailed = totalFailed;
       this.cellcFailed = cellcFailed;
       this.celltelFailed = celltelFailed;
       this.safaricomFailed = safaricomFailed;
       this.otherFailed = otherFailed;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dbdate", column=@Column(name="dbdate", nullable=false, length=10) ), 
        @AttributeOverride(name="user", column=@Column(name="user", nullable=false, length=100) ), 
        @AttributeOverride(name="rule", column=@Column(name="rule", nullable=false, length=100) ), 
        @AttributeOverride(name="message", column=@Column(name="message", nullable=false, length=65535) ) } )
    public TstatsoutId getId() {
        return this.id;
    }
    
    public void setId(TstatsoutId id) {
        this.id = id;
    }

    
    @Column(name="total", nullable=false)
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }

    
    @Column(name="safaricom", nullable=false)
    public long getSafaricom() {
        return this.safaricom;
    }
    
    public void setSafaricom(long safaricom) {
        this.safaricom = safaricom;
    }

    
    @Column(name="cellc", nullable=false)
    public long getCellc() {
        return this.cellc;
    }
    
    public void setCellc(long cellc) {
        this.cellc = cellc;
    }

    
    @Column(name="celltel", nullable=false)
    public long getCelltel() {
        return this.celltel;
    }
    
    public void setCelltel(long celltel) {
        this.celltel = celltel;
    }

    
    @Column(name="other", nullable=false)
    public long getOther() {
        return this.other;
    }
    
    public void setOther(long other) {
        this.other = other;
    }

    
    @Column(name="total_failed")
    public Long getTotalFailed() {
        return this.totalFailed;
    }
    
    public void setTotalFailed(Long totalFailed) {
        this.totalFailed = totalFailed;
    }

    
    @Column(name="cellc_failed")
    public Long getCellcFailed() {
        return this.cellcFailed;
    }
    
    public void setCellcFailed(Long cellcFailed) {
        this.cellcFailed = cellcFailed;
    }

    
    @Column(name="celltel_failed", nullable=false)
    public long getCelltelFailed() {
        return this.celltelFailed;
    }
    
    public void setCelltelFailed(long celltelFailed) {
        this.celltelFailed = celltelFailed;
    }

    
    @Column(name="safaricom_failed")
    public Long getSafaricomFailed() {
        return this.safaricomFailed;
    }
    
    public void setSafaricomFailed(Long safaricomFailed) {
        this.safaricomFailed = safaricomFailed;
    }

    
    @Column(name="other_failed")
    public Long getOtherFailed() {
        return this.otherFailed;
    }
    
    public void setOtherFailed(Long otherFailed) {
        this.otherFailed = otherFailed;
    }




}


