package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TstatsinId generated by hbm2java
 */
@Embeddable
public class TstatsinId  implements java.io.Serializable {


     private Date dbdate;
     private String sourceAddr;

    public TstatsinId() {
    }

    public TstatsinId(Date dbdate, String sourceAddr) {
       this.dbdate = dbdate;
       this.sourceAddr = sourceAddr;
    }
   


    @Column(name="dbdate", nullable=false, length=10)
    public Date getDbdate() {
        return this.dbdate;
    }
    
    public void setDbdate(Date dbdate) {
        this.dbdate = dbdate;
    }


    @Column(name="source_addr", nullable=false, length=20)
    public String getSourceAddr() {
        return this.sourceAddr;
    }
    
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TstatsinId) ) return false;
		 TstatsinId castOther = ( TstatsinId ) other; 
         
		 return ( (this.getDbdate()==castOther.getDbdate()) || ( this.getDbdate()!=null && castOther.getDbdate()!=null && this.getDbdate().equals(castOther.getDbdate()) ) )
 && ( (this.getSourceAddr()==castOther.getSourceAddr()) || ( this.getSourceAddr()!=null && castOther.getSourceAddr()!=null && this.getSourceAddr().equals(castOther.getSourceAddr()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDbdate() == null ? 0 : this.getDbdate().hashCode() );
         result = 37 * result + ( getSourceAddr() == null ? 0 : this.getSourceAddr().hashCode() );
         return result;
   }   


}


