package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TsystemFeatures generated by hbm2java
 */
@Entity
@Table(name="tSystemFeatures"
    ,catalog="dbSMS"
)
public class TsystemFeatures  implements java.io.Serializable {


     private Integer id;
     private String feature;
     private String featureDesc;
     private Boolean enable;
     private Date dbDate;

    public TsystemFeatures() {
    }

    public TsystemFeatures(String feature, String featureDesc, Boolean enable, Date dbDate) {
       this.feature = feature;
       this.featureDesc = featureDesc;
       this.enable = enable;
       this.dbDate = dbDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="feature", length=200)
    public String getFeature() {
        return this.feature;
    }
    
    public void setFeature(String feature) {
        this.feature = feature;
    }

    
    @Column(name="featureDesc", length=250)
    public String getFeatureDesc() {
        return this.featureDesc;
    }
    
    public void setFeatureDesc(String featureDesc) {
        this.featureDesc = featureDesc;
    }

    
    @Column(name="enable")
    public Boolean getEnable() {
        return this.enable;
    }
    
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dbDate", length=19)
    public Date getDbDate() {
        return this.dbDate;
    }
    
    public void setDbDate(Date dbDate) {
        this.dbDate = dbDate;
    }




}


