package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TunsubscriptionData generated by hbm2java
 */
@Entity
@Table(name="tUnsubscriptionData"
    ,catalog="dbSMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="mobile") 
)
public class TunsubscriptionData  implements java.io.Serializable {


     private Long id;
     private String mobile;
     private String sms;
     private short shortCode;
     private Date unsubscriptionDate;
     private boolean active;

    public TunsubscriptionData() {
    }

	
    public TunsubscriptionData(String mobile, String sms, short shortCode, boolean active) {
        this.mobile = mobile;
        this.sms = sms;
        this.shortCode = shortCode;
        this.active = active;
    }
    public TunsubscriptionData(String mobile, String sms, short shortCode, Date unsubscriptionDate, boolean active) {
       this.mobile = mobile;
       this.sms = sms;
       this.shortCode = shortCode;
       this.unsubscriptionDate = unsubscriptionDate;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="mobile", unique=true, nullable=false, length=13)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="sms", nullable=false, length=65535)
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }

    
    @Column(name="short_code", nullable=false)
    public short getShortCode() {
        return this.shortCode;
    }
    
    public void setShortCode(short shortCode) {
        this.shortCode = shortCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="unsubscriptionDate", length=19)
    public Date getUnsubscriptionDate() {
        return this.unsubscriptionDate;
    }
    
    public void setUnsubscriptionDate(Date unsubscriptionDate) {
        this.unsubscriptionDate = unsubscriptionDate;
    }

    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }




}


