package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TunsubscriptionSetup generated by hbm2java
 */
@Entity
@Table(name="tUnsubscriptionSetup"
    ,catalog="dbSMS"
)
public class TunsubscriptionSetup  implements java.io.Serializable {


     private Integer id;
     private String keyword;
     private String reply;
     private boolean status;

    public TunsubscriptionSetup() {
    }

    public TunsubscriptionSetup(String keyword, String reply, boolean status) {
       this.keyword = keyword;
       this.reply = reply;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="keyword", nullable=false, length=100)
    public String getKeyword() {
        return this.keyword;
    }
    
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    
    @Column(name="reply", nullable=false, length=100)
    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


