package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tusersmsout generated by hbm2java
 */
@Entity
@Table(name="tUSERSMSOUT"
    ,catalog="dbSMS"
)
public class Tusersmsout  implements java.io.Serializable {


     private Long id;
     private Long userid;
     private byte status;
     private String shortMessage;
     private String sourceAddr;
     private String destinationAddr;
     private String timeSubmitted;
     private String timeProcessed;

    public Tusersmsout() {
    }

	
    public Tusersmsout(byte status) {
        this.status = status;
    }
    public Tusersmsout(Long userid, byte status, String shortMessage, String sourceAddr, String destinationAddr, String timeSubmitted, String timeProcessed) {
       this.userid = userid;
       this.status = status;
       this.shortMessage = shortMessage;
       this.sourceAddr = sourceAddr;
       this.destinationAddr = destinationAddr;
       this.timeSubmitted = timeSubmitted;
       this.timeProcessed = timeProcessed;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="userid")
    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }

    
    @Column(name="short_message", length=200)
    public String getShortMessage() {
        return this.shortMessage;
    }
    
    public void setShortMessage(String shortMessage) {
        this.shortMessage = shortMessage;
    }

    
    @Column(name="source_addr", length=20)
    public String getSourceAddr() {
        return this.sourceAddr;
    }
    
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr;
    }

    
    @Column(name="destination_addr", length=15)
    public String getDestinationAddr() {
        return this.destinationAddr;
    }
    
    public void setDestinationAddr(String destinationAddr) {
        this.destinationAddr = destinationAddr;
    }

    
    @Column(name="time_submitted", length=14)
    public String getTimeSubmitted() {
        return this.timeSubmitted;
    }
    
    public void setTimeSubmitted(String timeSubmitted) {
        this.timeSubmitted = timeSubmitted;
    }

    
    @Column(name="time_processed", length=14)
    public String getTimeProcessed() {
        return this.timeProcessed;
    }
    
    public void setTimeProcessed(String timeProcessed) {
        this.timeProcessed = timeProcessed;
    }




}


