package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tusersmsschedule generated by hbm2java
 */
@Entity
@Table(name="tUSERSMSSCHEDULE"
    ,catalog="dbSMS"
)
public class Tusersmsschedule  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String source;
     private String message;
     private String dest;
     private String sentby;
     private Date sendTime;

    public Tusersmsschedule() {
    }

    public Tusersmsschedule(String username, String source, String message, String dest, String sentby, Date sendTime) {
       this.username = username;
       this.source = source;
       this.message = message;
       this.dest = dest;
       this.sentby = sentby;
       this.sendTime = sendTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="source", nullable=false, length=20)
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }

    
    @Column(name="message", nullable=false, length=65535)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="dest", nullable=false, length=20)
    public String getDest() {
        return this.dest;
    }
    
    public void setDest(String dest) {
        this.dest = dest;
    }

    
    @Column(name="sentby", nullable=false, length=50)
    public String getSentby() {
        return this.sentby;
    }
    
    public void setSentby(String sentby) {
        this.sentby = sentby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sendTime", nullable=false, length=19)
    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }




}


