package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tuseraddressbook generated by hbm2java
 */
@Entity
@Table(name="tUSERADDRESSBOOK"
    ,catalog="dbSMS"
)
public class Tuseraddressbook  implements java.io.Serializable {


     private Long id;
     private long userId;
     private String groupName;
     private String contactName;
     private String contactNumber;
     private String contactEmail;

    public Tuseraddressbook() {
    }
    
 public Tuseraddressbook(long userId, String groupName, String contactName, String contactNumber, String contactEmail) {
       this.userId = userId;
       this.groupName = groupName;
       this.contactName = contactName;
       this.contactNumber = contactNumber;
       this.contactEmail = contactEmail;
    }

    public Tuseraddressbook(long userId,String groupName, String contactName, String contactNumber) {
       this.userId = userId;
        this.groupName = groupName;
        this.contactName = contactName;
        this.contactNumber = contactNumber;
    }
 
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="user_id", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    
    @Column(name="group_name", nullable=false, length=50)
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    
    @Column(name="contact_name", nullable=false, length=50)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    
    @Column(name="contact_number", nullable=false, length=15)
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    
    @Column(name="contact_email", length=100)
    public String getContactEmail() {
        return this.contactEmail;
    }
   
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }




}


