package com.mspace1.model;
// Generated Nov 3, 2016 10:30:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tusersmsin generated by hbm2java
 */
@Entity
@Table(name="tUSERSMSIN"
    ,catalog="dbSMS"
)
public class Tusersmsin  implements java.io.Serializable {


     private Long id;
     private Long userid;
     private Long parentSmsId;
     private String shortMessage;
     private Character data;
     private String sourceAddr;
     private String destinationAddr;
     private String esmClass;
     private String timereceived;

    public Tusersmsin() {
    }

    public Tusersmsin(Long userid, Long parentSmsId, String shortMessage, Character data, String sourceAddr, String destinationAddr, String esmClass, String timereceived) {
       this.userid = userid;
       this.parentSmsId = parentSmsId;
       this.shortMessage = shortMessage;
       this.data = data;
       this.sourceAddr = sourceAddr;
       this.destinationAddr = destinationAddr;
       this.esmClass = esmClass;
       this.timereceived = timereceived;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="userid")
    public Long getUserid() {
        return this.userid;
    }
    
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    
    @Column(name="parent_sms_id")
    public Long getParentSmsId() {
        return this.parentSmsId;
    }
    
    public void setParentSmsId(Long parentSmsId) {
        this.parentSmsId = parentSmsId;
    }

    
    @Column(name="short_message", length=65535)
    public String getShortMessage() {
        return this.shortMessage;
    }
    
    public void setShortMessage(String shortMessage) {
        this.shortMessage = shortMessage;
    }

    
    @Column(name="data", length=1)
    public Character getData() {
        return this.data;
    }
    
    public void setData(Character data) {
        this.data = data;
    }

    
    @Column(name="source_addr", length=20)
    public String getSourceAddr() {
        return this.sourceAddr;
    }
    
    public void setSourceAddr(String sourceAddr) {
        this.sourceAddr = sourceAddr;
    }

    
    @Column(name="destination_addr", length=100)
    public String getDestinationAddr() {
        return this.destinationAddr;
    }
    
    public void setDestinationAddr(String destinationAddr) {
        this.destinationAddr = destinationAddr;
    }

    
    @Column(name="esm_class", length=2)
    public String getEsmClass() {
        return this.esmClass;
    }
    
    public void setEsmClass(String esmClass) {
        this.esmClass = esmClass;
    }

    
    @Column(name="timereceived", length=14)
    public String getTimereceived() {
        return this.timereceived;
    }
    
    public void setTimereceived(String timereceived) {
        this.timereceived = timereceived;
    }




}


