package model2;
// Generated Nov 2, 2016 10:54:07 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Tuser generated by hbm2java
 */
@Entity
@Table(name="tUSER"
    ,catalog="dbSMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Tuser  implements java.io.Serializable {


     private Long id;
     private String username;
     private String password;
     private String agent;
     private long maxDaily;
     private long maxWeekly;
     private long maxMonthly;
     private long maxTotal;
     private boolean loggedIn;
     private Date loggedInTime;
     private String msg;
     private String destinationAddr;
     private Character admin;
     private String shortCodes;
     private Date startDate;
     private Date endDate;
     private Date lastReceived;
     private Date lastSend;
     private long lastReceivedId;
     private Long lastSentId;
     private Long smsCountToday;
     private Long smsCountWeek;
     private Long smsCountMonth;
     private Long smsCountTotal;
     private Long receivedTotal;
     private Long receivedMonth;
     private Long receivedWeek;
     private Long receivedToday;
     private String name;
     private String contactNumber;
     private String contractNum;
     private String staffNo;
     private String firstname;
     private String surname;
     private Integer departmentNo;
     private Integer jobTitleNo;
     private String reportsTo;
     private String emailAddress;
     private String notes;
     private String userId;
     private Date dateUpdated;
     private Character taskadmin;
     private String organization;
     private Boolean enableEmailAlert;
     private int alertThreshold;
     private Integer superAccountId;

    public Tuser() {
    }

	
    public Tuser(String username, String password, String agent, long maxDaily, long maxWeekly, long maxMonthly, long maxTotal, boolean loggedIn, Date loggedInTime, long lastReceivedId, String staffNo, String firstname, String surname, Date dateUpdated, int alertThreshold) {
        this.username = username;
        this.password = password;
        this.agent = agent;
        this.maxDaily = maxDaily;
        this.maxWeekly = maxWeekly;
        this.maxMonthly = maxMonthly;
        this.maxTotal = maxTotal;
        this.loggedIn = loggedIn;
        this.loggedInTime = loggedInTime;
        this.lastReceivedId = lastReceivedId;
        this.staffNo = staffNo;
        this.firstname = firstname;
        this.surname = surname;
        this.dateUpdated = dateUpdated;
        this.alertThreshold = alertThreshold;
    }
    public Tuser(String username, String password, String agent, long maxDaily, long maxWeekly, long maxMonthly, long maxTotal, boolean loggedIn, Date loggedInTime, String msg, String destinationAddr, Character admin, String shortCodes, Date startDate, Date endDate, Date lastReceived, Date lastSend, long lastReceivedId, Long lastSentId, Long smsCountToday, Long smsCountWeek, Long smsCountMonth, Long smsCountTotal, Long receivedTotal, Long receivedMonth, Long receivedWeek, Long receivedToday, String name, String contactNumber, String contractNum, String staffNo, String firstname, String surname, Integer departmentNo, Integer jobTitleNo, String reportsTo, String emailAddress, String notes, String userId, Date dateUpdated, Character taskadmin, String organization, Boolean enableEmailAlert, int alertThreshold, Integer superAccountId) {
       this.username = username;
       this.password = password;
       this.agent = agent;
       this.maxDaily = maxDaily;
       this.maxWeekly = maxWeekly;
       this.maxMonthly = maxMonthly;
       this.maxTotal = maxTotal;
       this.loggedIn = loggedIn;
       this.loggedInTime = loggedInTime;
       this.msg = msg;
       this.destinationAddr = destinationAddr;
       this.admin = admin;
       this.shortCodes = shortCodes;
       this.startDate = startDate;
       this.endDate = endDate;
       this.lastReceived = lastReceived;
       this.lastSend = lastSend;
       this.lastReceivedId = lastReceivedId;
       this.lastSentId = lastSentId;
       this.smsCountToday = smsCountToday;
       this.smsCountWeek = smsCountWeek;
       this.smsCountMonth = smsCountMonth;
       this.smsCountTotal = smsCountTotal;
       this.receivedTotal = receivedTotal;
       this.receivedMonth = receivedMonth;
       this.receivedWeek = receivedWeek;
       this.receivedToday = receivedToday;
       this.name = name;
       this.contactNumber = contactNumber;
       this.contractNum = contractNum;
       this.staffNo = staffNo;
       this.firstname = firstname;
       this.surname = surname;
       this.departmentNo = departmentNo;
       this.jobTitleNo = jobTitleNo;
       this.reportsTo = reportsTo;
       this.emailAddress = emailAddress;
       this.notes = notes;
       this.userId = userId;
       this.dateUpdated = dateUpdated;
       this.taskadmin = taskadmin;
       this.organization = organization;
       this.enableEmailAlert = enableEmailAlert;
       this.alertThreshold = alertThreshold;
       this.superAccountId = superAccountId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="agent", nullable=false, length=100)
    public String getAgent() {
        return this.agent;
    }
    
    public void setAgent(String agent) {
        this.agent = agent;
    }

    
    @Column(name="max_daily", nullable=false)
    public long getMaxDaily() {
        return this.maxDaily;
    }
    
    public void setMaxDaily(long maxDaily) {
        this.maxDaily = maxDaily;
    }

    
    @Column(name="max_weekly", nullable=false)
    public long getMaxWeekly() {
        return this.maxWeekly;
    }
    
    public void setMaxWeekly(long maxWeekly) {
        this.maxWeekly = maxWeekly;
    }

    
    @Column(name="max_monthly", nullable=false)
    public long getMaxMonthly() {
        return this.maxMonthly;
    }
    
    public void setMaxMonthly(long maxMonthly) {
        this.maxMonthly = maxMonthly;
    }

    
    @Column(name="max_total", nullable=false)
    public long getMaxTotal() {
        return this.maxTotal;
    }
    
    public void setMaxTotal(long maxTotal) {
        this.maxTotal = maxTotal;
    }

    
    @Column(name="logged_in", nullable=false)
    public boolean isLoggedIn() {
        return this.loggedIn;
    }
    
    public void setLoggedIn(boolean loggedIn) {
        this.loggedIn = loggedIn;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="logged_in_time", nullable=false, length=19)
    public Date getLoggedInTime() {
        return this.loggedInTime;
    }
    
    public void setLoggedInTime(Date loggedInTime) {
        this.loggedInTime = loggedInTime;
    }

    
    @Column(name="msg", length=100)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }

    
    @Column(name="destination_addr", length=20)
    public String getDestinationAddr() {
        return this.destinationAddr;
    }
    
    public void setDestinationAddr(String destinationAddr) {
        this.destinationAddr = destinationAddr;
    }

    
    @Column(name="admin", length=1)
    public Character getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Character admin) {
        this.admin = admin;
    }

    
    @Column(name="short_codes", length=250)
    public String getShortCodes() {
        return this.shortCodes;
    }
    
    public void setShortCodes(String shortCodes) {
        this.shortCodes = shortCodes;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_received", length=19)
    public Date getLastReceived() {
        return this.lastReceived;
    }
    
    public void setLastReceived(Date lastReceived) {
        this.lastReceived = lastReceived;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_send", length=19)
    public Date getLastSend() {
        return this.lastSend;
    }
    
    public void setLastSend(Date lastSend) {
        this.lastSend = lastSend;
    }

    
    @Column(name="last_received_id", nullable=false)
    public long getLastReceivedId() {
        return this.lastReceivedId;
    }
    
    public void setLastReceivedId(long lastReceivedId) {
        this.lastReceivedId = lastReceivedId;
    }

    
    @Column(name="last_sent_id")
    public Long getLastSentId() {
        return this.lastSentId;
    }
    
    public void setLastSentId(Long lastSentId) {
        this.lastSentId = lastSentId;
    }

    
    @Column(name="sms_count_today")
    public Long getSmsCountToday() {
        return this.smsCountToday;
    }
    
    public void setSmsCountToday(Long smsCountToday) {
        this.smsCountToday = smsCountToday;
    }

    
    @Column(name="sms_count_week")
    public Long getSmsCountWeek() {
        return this.smsCountWeek;
    }
    
    public void setSmsCountWeek(Long smsCountWeek) {
        this.smsCountWeek = smsCountWeek;
    }

    
    @Column(name="sms_count_month")
    public Long getSmsCountMonth() {
        return this.smsCountMonth;
    }
    
    public void setSmsCountMonth(Long smsCountMonth) {
        this.smsCountMonth = smsCountMonth;
    }

    
    @Column(name="sms_count_total")
    public Long getSmsCountTotal() {
        return this.smsCountTotal;
    }
    
    public void setSmsCountTotal(Long smsCountTotal) {
        this.smsCountTotal = smsCountTotal;
    }

    
    @Column(name="received_total")
    public Long getReceivedTotal() {
        return this.receivedTotal;
    }
    
    public void setReceivedTotal(Long receivedTotal) {
        this.receivedTotal = receivedTotal;
    }

    
    @Column(name="received_month")
    public Long getReceivedMonth() {
        return this.receivedMonth;
    }
    
    public void setReceivedMonth(Long receivedMonth) {
        this.receivedMonth = receivedMonth;
    }

    
    @Column(name="received_week")
    public Long getReceivedWeek() {
        return this.receivedWeek;
    }
    
    public void setReceivedWeek(Long receivedWeek) {
        this.receivedWeek = receivedWeek;
    }

    
    @Column(name="received_today")
    public Long getReceivedToday() {
        return this.receivedToday;
    }
    
    public void setReceivedToday(Long receivedToday) {
        this.receivedToday = receivedToday;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="contact_number", length=20)
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    
    @Column(name="contract_num", length=20)
    public String getContractNum() {
        return this.contractNum;
    }
    
    public void setContractNum(String contractNum) {
        this.contractNum = contractNum;
    }

    
    @Column(name="staff_no", nullable=false, length=100)
    public String getStaffNo() {
        return this.staffNo;
    }
    
    public void setStaffNo(String staffNo) {
        this.staffNo = staffNo;
    }

    
    @Column(name="firstname", nullable=false, length=100)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="surname", nullable=false, length=100)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="department_no")
    public Integer getDepartmentNo() {
        return this.departmentNo;
    }
    
    public void setDepartmentNo(Integer departmentNo) {
        this.departmentNo = departmentNo;
    }

    
    @Column(name="job_title_no")
    public Integer getJobTitleNo() {
        return this.jobTitleNo;
    }
    
    public void setJobTitleNo(Integer jobTitleNo) {
        this.jobTitleNo = jobTitleNo;
    }

    
    @Column(name="reports_to", length=100)
    public String getReportsTo() {
        return this.reportsTo;
    }
    
    public void setReportsTo(String reportsTo) {
        this.reportsTo = reportsTo;
    }

    
    @Column(name="email_address", length=100)
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="user_id", length=100)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_updated", nullable=false, length=19)
    public Date getDateUpdated() {
        return this.dateUpdated;
    }
    
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    
    @Column(name="taskadmin", length=1)
    public Character getTaskadmin() {
        return this.taskadmin;
    }
    
    public void setTaskadmin(Character taskadmin) {
        this.taskadmin = taskadmin;
    }

    
    @Column(name="organization")
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    
    @Column(name="enable_email_alert")
    public Boolean getEnableEmailAlert() {
        return this.enableEmailAlert;
    }
    
    public void setEnableEmailAlert(Boolean enableEmailAlert) {
        this.enableEmailAlert = enableEmailAlert;
    }

    
    @Column(name="alertThreshold", nullable=false)
    public int getAlertThreshold() {
        return this.alertThreshold;
    }
    
    public void setAlertThreshold(int alertThreshold) {
        this.alertThreshold = alertThreshold;
    }

    
    @Column(name="super_account_id")
    public Integer getSuperAccountId() {
        return this.superAccountId;
    }
    
    public void setSuperAccountId(Integer superAccountId) {
        this.superAccountId = superAccountId;
    }




}


